<?php
$status = new OpCacheGUI\OpCache\Status($byteFormatter);
$classCycler = new OpCacheGUI\Presentation\ClassCycler(['odd', 'even']);

$directories = [];
foreach($status->getCachedScripts() as $data) {
    $directories[dirname($data['full_path'])][basename($data['full_path'])] = $data;
}
?>
<div>
    <article class="cols-0">
    <h2>Clear cache</h2>
        <div style="border:#333333; padding: 10px;overflow: visible; height: 70px;">
        <form action="/reset" method="post" id="reset" data-confirmation="<?= $translator->translate('confirmation.reset'); ?>" data-yes="<?= $translator->translate('confirmation.yes'); ?>" data-no="<?= $translator->translate('confirmation.no'); ?>">
            <button><a href="javascript:document.location.reload();">F5</a></button>
            <input type="hidden" name="csrfToken" value="<?= $csrfToken->get(); ?>">
            <input type="submit" name="submit" value="<?= $translator->translate('reset.submit'); ?>">
        </form>
        </div>
    </article>
</div>
<article class="cols-1">
    <h2><?= $translator->translate('scripts.title'); ?></h2>
    <table id="cached">
        <tbody>
            <?php if (!count($status->getCachedScripts())) { ?>
                <tr class="<?= $classCycler->next(); ?>">
                    <td class="empty" colspan="5"><?= $translator->translate('scripts.empty'); ?></td>
                </tr>
            <?php } else { ?>
                <?php $i = 0; ?>
                <?php foreach ($directories as $directory => $scripts) { ?>
                    <tr class="<?= $classCycler->next(); ?>">
                        <td colspan="6" class="directory" data-directoryid="<?= ++$i; ?>"><img src="/style/toggle-expand.png" alt="+"><?= $directory . sprintf($translator->translate('scripts.directory.script_count'), count($scripts)); ?></td>
                    </tr>
                    <tr class="script heading" data-directoryid="<?= $i; ?>">
                        <th class="full_path"><?= $translator->translate('scripts.full_path'); ?></th>
                        <th class="hits"><?= $translator->translate('scripts.hits'); ?></th>
                        <th class="memory_consumption"><?= $translator->translate('scripts.memory_consumption'); ?></th>
                        <th class="last_used_timestamp"><?= $translator->translate('scripts.last_used_timestamp'); ?></th>
                        <th class="timestamp"><?= $translator->translate('scripts.timestamp'); ?></th>
                        <th class="invalidate"></th>
                    </tr>
                    <?php foreach ($scripts as $filename => $script) { ?>
                        <tr class="script" data-directoryid="<?= $i; ?>">
                            <td class="full_path"><?= $filename; ?></td>
                            <td class="hits"><?= $script['hits']; ?></td>
                            <td class="memory_consumption"><?= $script['memory_consumption']; ?></td>
                            <td class="last_used_timestamp"><?= $script['last_used_timestamp']; ?></td>
                            <td class="timestamp"><?= $script['timestamp']; ?></td>
                            <td class="invalidate">
                                <form action="/invalidate" method="post">
                                    <input type="hidden" name="csrfToken" value="<?= $csrfToken->get(); ?>">
                                    <input type="hidden" name="key" value="<?= $script['full_path']; ?>">
                                    <input type="submit" name="submit" value="<?= $translator->translate('script.invalidate'); ?>">
                                </form>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
<?php $apcuCache = function_exists( 'apc_cache_info' )? @apc_cache_info() : false; ?>
<?php if( $apcuCache ){ ?>
<h2>APCu cache</h2>
<table id="cached">
	<tr class="script">
		<th >Key</th><th>Mem_size</th><th>Created</th>
	</tr>
<?php if( !empty( $apcuCache['cache_list']  ) ) foreach( $apcuCache['cache_list'] as $num => $cpage ){ ?>
	<tr>
		<td class="directory" data-directory="<?= 'apcu_' . $num ?>"><img src="/style/toggle-expand.png" alt="+"><?= $cpage['key'] ?></td><td><?= $cpage['mem_size'] ?></td><td><?=$cpage['ctime']?></td>
	</tr>
    <tr class="script" data-directory="<?= 'apcu_' . $num ?>"><td><?= json_encode( apc_fetch( $cpage['key'] ) ) ?></td></tr>
<?php } ?>

</table>
<?php } ?>
</article>

